version: "3"
services:
  contato:
    build:
      context: ./contato-fiap
      dockerfile: Dockerfile
      args:
        version: 1
    image: contatos-service-api-metrics
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Server="mssql-server"
      - Database=ContatosDb
      - Password="1q2w3e4r@#$"
    networks:
      - default
    depends_on:
      rabbitmq:
        condition: service_started
      sqlserver:
        condition: service_healthy
        
  regiao:
    build:
      context: ./regiao-fiap
      dockerfile: Dockerfile
      args:
        version: 1
    image: regiao-api-metrics
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Server="mssql-server"
      - Database=RegioesDb
      - Password="1q2w3e4r@#$"
    networks:
      - default
    depends_on:
      rabbitmq:
        condition: service_started
      sqlserver:
        condition: service_healthy

  sqlserver:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
      args:
        version: 1
    image: sqlserver-local
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    expose:
      - "1433"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P '1q2w3e4r@#$' -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image: prometheus-local
    restart: always
    ports:
      - "9090:9090"
    networks:
      - default
    volumes:
      - './prometheus/data:/data'

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: grafana-local
    restart: always
    ports:
      - "3000:3000"
    networks:
      - default

  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq"
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - default

networks:
  default:
    driver: bridge
