global:
    scrape_interval: 10s

scrape_configs: 
  - job_name: "contatos-microsservice"
    metrics_path: /metrics
    static_configs:
      - targets: ["contato:8080"]
        
  - job_name: "regioes-microsservice"
    metrics_path: /metrics
    static_configs:
      - targets: [ "regiao:8080" ]